version: '3.8'
services:
  web:
    image: https-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./certs:/certs:rw
      - ./html:/usr/share/nginx/html:ro
    environment:
      - DOMAIN=${DOMAIN:-localhost}  # 環境変数から取得、未設定時はlocalhostを使用
      - SSL_CERTIFICATE=/certs/${DOMAIN:-localhost}/cert.pem
      - SSL_CERTIFICATE_KEY=/certs/${DOMAIN:-localhost}/key.pem
