version: '3.8'
services:
  web:
    image: https-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - certs:/certs:rw
      - ./html:/usr/share/nginx/html:ro
    environment:
      - DOMAIN=${DOMAIN:-localhost}  # 環境変数から取得、未設定時はlocalhostを使用
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/conf.d
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d

volumes:
  certs:
    name: https-nginx-certs
